export const SET_CHI_TIET_PHONG_VE = "SET_CHI_TIET_PHONG_VE";
export const DAT_GHE = "DAT_GHE";
export const DAT_VE_HOAN_TAT = "DAT_VE_HOAN_TAT";
export const KIEM_TRA_TRANG_DAT_VE = "KIEM_TRA_TRANG_DAT_VE";
export const CHUYEN_TAB ='CHUYEN_TAB'
export const CHANGE_TAB_ACTIVE='CHANGE_TAB_ACTIVE'
